[parity]
chain = "validator.json"
base_path = "/node0"

[network]
port = 30300


[rpc]
port = 8545
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]

[websockets]
port = 8452
disable = false

[ipc]
disable = true

[account]
unlock = ["0x5419b10eabe5346923507d63dfab6ea11a72abc8"]
password = ["password.File"]

[mining]
engine_signer = "0x5419b10eabe5346923507d63dfab6ea11a72abc8"
reseal_on_txs = "none"
force_sealing = true
usd_per_tx = "0"
tx_queue_size = 8192

[misc]
logging = "own_tx,shutdown=trace"
