[parity]
chain = "./validator.json"
base_path = "/node0"

[network]
port = 30300


[rpc]
port = 8545
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]

[websockets]
port = 8452
disable = false

[ipc]
disable = true

[account]
unlock = ["0xa35F71ab0bfc20418392Cc7580Ff4b312fD6f1E0"]
password = ["./password.file"]

[mining]
engine_signer = "0xa35F71ab0bfc20418392Cc7580Ff4b312fD6f1E0"
reseal_on_txs = "none"
force_sealing = true
usd_per_tx = "0"
tx_queue_size = 8192

[misc]
logging = "own_tx,shutdown=trace"
